import type { Municipality } from "./types";

// Static mock data for the prototype. No backend — all hardcoded.
export const municipalities: Municipality[] = [
  {
    id: 1,
    city: "Manhattan",
    state: "NY",
    lat: 40.7831,
    lng: -73.9712,
    population: "1,629,000",
    roadBudget: "$8.1M",
    roadbotics: true,
    status: "In Discussion",
    lastContact: "2026-05-28",
    rfpActive: true,
    rfpDeadline: "2026-07-15",
    rfpLink: "https://example.gov/rfp/manhattan-road-assessment",
    notes: "Spoke with Dir. of Public Works. Interested in pilot.",
    contactLog: [
      { date: "2026-04-10", note: "Cold outreach email to procurement office." },
      { date: "2026-05-02", note: "Intro call scheduled with Public Works." },
      { date: "2026-05-28", note: "Pilot scope discussed. Awaiting budget confirmation." },
    ],
    procurementNotes:
      "Prefers vendors on NYC MWBE list. Procurement cycle aligns with Q3 fiscal planning.",
    followUpDate: "2026-06-12",
  },
  {
    id: 2,
    city: "Brooklyn",
    state: "NY",
    lat: 40.6782,
    lng: -73.9442,
    population: "2,590,000",
    roadBudget: "$12.4M",
    roadbotics: true,
    status: "Contacted",
    lastContact: "2026-06-01",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "Initial email sent. Awaiting response.",
    contactLog: [
      { date: "2026-05-20", note: "LinkedIn connection with Borough engineer." },
      { date: "2026-06-01", note: "Sent capabilities deck via email." },
    ],
    procurementNotes: "Shares procurement infrastructure with citywide DOT.",
    followUpDate: "2026-06-15",
  },
  {
    id: 3,
    city: "Jersey City",
    state: "NJ",
    lat: 40.7178,
    lng: -74.0431,
    population: "292,000",
    roadBudget: "$3.6M",
    roadbotics: true,
    status: "Proposal Sent",
    lastContact: "2026-05-22",
    rfpActive: true,
    rfpDeadline: "2026-06-20",
    rfpLink: "https://example.gov/rfp/jersey-city-pavement",
    notes: "Proposal submitted for pavement condition survey.",
    contactLog: [
      { date: "2026-03-15", note: "Former RoadBotics account — re-engagement call." },
      { date: "2026-04-28", note: "RFP released; confirmed eligibility." },
      { date: "2026-05-22", note: "Formal proposal submitted." },
    ],
    procurementNotes: "Decision expected within 30 days of RFP close.",
    followUpDate: "2026-06-18",
  },
  {
    id: 4,
    city: "Newark",
    state: "NJ",
    lat: 40.7357,
    lng: -74.1724,
    population: "311,000",
    roadBudget: "$4.2M",
    roadbotics: false,
    status: "Not Contacted",
    lastContact: "—",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "Identified via census/budget research. No contact yet.",
    contactLog: [],
    procurementNotes: "No known procurement contact. Research city council minutes.",
    followUpDate: null,
  },
  {
    id: 5,
    city: "Baltimore",
    state: "MD",
    lat: 39.2904,
    lng: -76.6122,
    population: "569,000",
    roadBudget: "$6.8M",
    roadbotics: true,
    status: "In Discussion",
    lastContact: "2026-05-30",
    rfpActive: true,
    rfpDeadline: "2026-06-10",
    rfpLink: "https://example.gov/rfp/baltimore-road-condition",
    notes: "Strong interest. RFP deadline approaching fast.",
    contactLog: [
      { date: "2026-04-22", note: "Reconnected with former RoadBotics champion." },
      { date: "2026-05-15", note: "Technical demo delivered to DOT staff." },
      { date: "2026-05-30", note: "Discussed RFP requirements and timeline." },
    ],
    procurementNotes: "Needs COI and state vendor registration before award.",
    followUpDate: "2026-06-06",
  },
  {
    id: 6,
    city: "Arlington",
    state: "VA",
    lat: 38.8816,
    lng: -77.0910,
    population: "238,000",
    roadBudget: "$5.1M",
    roadbotics: false,
    status: "Contacted",
    lastContact: "2026-05-18",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "Public Works open to a discovery call.",
    contactLog: [
      { date: "2026-05-05", note: "Referral intro from regional planning contact." },
      { date: "2026-05-18", note: "Brief intro email exchange." },
    ],
    procurementNotes: "County-level procurement. Cooperative purchasing possible.",
    followUpDate: "2026-06-20",
  },
  {
    id: 7,
    city: "Alexandria",
    state: "VA",
    lat: 38.8048,
    lng: -77.0469,
    population: "159,000",
    roadBudget: "$3.9M",
    roadbotics: true,
    status: "Closed",
    lastContact: "2026-04-30",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "Pilot signed. Onboarding scheduled for Q3.",
    contactLog: [
      { date: "2026-02-10", note: "Former RoadBotics customer — warm re-engagement." },
      { date: "2026-03-20", note: "Pilot terms negotiated." },
      { date: "2026-04-30", note: "Agreement executed." },
    ],
    procurementNotes: "Pilot under small-purchase threshold; no formal RFP required.",
    followUpDate: "2026-07-01",
  },
  {
    id: 8,
    city: "Yonkers",
    state: "NY",
    lat: 40.9312,
    lng: -73.8987,
    population: "211,000",
    roadBudget: "$4.0M",
    roadbotics: false,
    status: "Not Contacted",
    lastContact: "—",
    rfpActive: true,
    rfpDeadline: "2026-08-05",
    rfpLink: "https://example.gov/rfp/yonkers-infrastructure",
    notes: "Active infrastructure RFP found. Good entry opportunity.",
    contactLog: [],
    procurementNotes: "RFP posted on state procurement portal. Pre-bid meeting TBD.",
    followUpDate: "2026-06-25",
  },
  {
    id: 9,
    city: "Rochester",
    state: "NY",
    lat: 43.1566,
    lng: -77.6088,
    population: "211,000",
    roadBudget: "$3.3M",
    roadbotics: true,
    status: "Contacted",
    lastContact: "2026-05-12",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "Former customer. Re-engaging after contract lapse.",
    contactLog: [
      { date: "2026-04-18", note: "Re-engagement email to prior point of contact." },
      { date: "2026-05-12", note: "Voicemail follow-up; awaiting callback." },
    ],
    procurementNotes: "Prior contract data may streamline re-procurement.",
    followUpDate: "2026-06-16",
  },
  {
    id: 10,
    city: "Trenton",
    state: "NJ",
    lat: 40.2206,
    lng: -74.7597,
    population: "90,000",
    roadBudget: "$2.1M",
    roadbotics: false,
    status: "Not Contacted",
    lastContact: "—",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "State capital. Smaller budget but strategic visibility.",
    contactLog: [],
    procurementNotes: "Research state cooperative purchasing agreements.",
    followUpDate: null,
  },
  {
    id: 11,
    city: "Richmond",
    state: "VA",
    lat: 37.5407,
    lng: -77.4360,
    population: "226,000",
    roadBudget: "$4.7M",
    roadbotics: false,
    status: "In Discussion",
    lastContact: "2026-05-26",
    rfpActive: true,
    rfpDeadline: "2026-09-01",
    rfpLink: "https://example.gov/rfp/richmond-pavement-mgmt",
    notes: "Evaluating pavement management vendors. Long runway.",
    contactLog: [
      { date: "2026-04-02", note: "Met at regional public works conference." },
      { date: "2026-05-26", note: "Follow-up call on pavement management goals." },
    ],
    procurementNotes: "Formal RFP expected; budget approved for FY27.",
    followUpDate: "2026-06-30",
  },
  {
    id: 12,
    city: "Silver Spring",
    state: "MD",
    lat: 38.9907,
    lng: -77.0261,
    population: "81,000",
    roadBudget: "$1.9M",
    roadbotics: true,
    status: "Proposal Sent",
    lastContact: "2026-05-24",
    rfpActive: false,
    rfpDeadline: null,
    rfpLink: null,
    notes: "Former customer. Renewal proposal under review.",
    contactLog: [
      { date: "2026-03-30", note: "Renewal conversation initiated." },
      { date: "2026-05-24", note: "Renewal proposal sent for review." },
    ],
    procurementNotes: "Managed via Montgomery County procurement.",
    followUpDate: "2026-06-14",
  },
];
